sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
- '2.7'
install:
- sudo pip install virtualenv
- virtualenv -p python2.7 ENV
- source ENV/bin/activate
- pip install -r requirements.txt
script: pytest